AUGMENTATION: true
IMAGE_SIZE:
- 224
- 224
- 3
BATCH_SIZE: 32
INCLUDE_TOP: false
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.001
EARLY_STOPPING_PATIENCE: 2
EARLY_STOPPING_MIN_DELTA: 0.002
LEARNING_RATE_SCHEDULER: ReduceLROnPlateau
LEARNING_RATE_SCHEDULER_FACTOR: 0.5
LEARNING_RATE_SCHEDULER_PATIENCE: 2
